name: Rust-Code CI/CD

on:
  push:
    branches: [ main ]
    paths:
    - 'rust-code/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup
        run: sudo snap install rustup --classic
      - run: rustup install stable
      - run: cargo install worker-build
      - run: worker-build --release
        working-directory: ./rust-code
      - run: cp wrangler.ci.toml wrangler.toml
        working-directory: ./rust-code
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_WORKER_API_TOKEN }}
          workingDirectory: 'rust-code'
